[project]
name = "stackguard-security"
description = "StackGuard Security Monitor Smart Contract"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements_dir = "./.requirements"

boot_contracts = [
	"ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.pox-3"
]

[contracts.security-monitor]
path = "contracts/security-monitor.clar"
clarity_version = 2
epoch = 2.1

[project.requirements]
stacks = "1.0.0"
